### ISSUE TITLE
3/31 todo

### ISSUE THREAD

**Issue by easyxxu** [easyxxu/testRepo#2]
## 일정
- [x] `9:00` 선배 특강
- [x] `13:00` 협업 특강 오늘도 개발자가 안 된다고 말했다.. 듣기..
## 할일
- [x] 협업 특강 복습
- [x] 나는 세계최고다 3번 외치기

**Comment by easyxxu** [comment]
이슈 클로즈 실습

**Comment by easyxxu** [comment]
이슈 클로즈
